# Generated by Django 5.2.14 on 2026-05-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='registration',
            table='registrations',
        ),
    ]
